name: 'Chromatic Deployment'

on: push

jobs:
  chromatic:
    name: 'Run Chromatic'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Instala dependencias con npm
      - run: npm ci

      # Construye el Storybook (esto crea la carpeta storybook-static)
      - run: npm run build-storybook

      # Publica la build usando el resultado generado
      - uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          storybookBuildDir: storybook-static
